### ISSUE TITLE
Documentation: Requirements are not 100% accurate

### ISSUE THREAD

**Issue by af778998** [FujitsuPrimergy/fujitsu-ansible-irmc-integration#1]
in the DOCUMENTATION.md stated under "Requirements" that only one extra module 'future' is needed.
This seems to be inaccurate.
At least 2 more modules are needed:
urllib3
requests-toolbelt

**Comment by akumch** [comment]
You are right, I forgot to mention 'requests' and 'urllib3' modules in requirements. Thanks, I'll add those shortly.
'requests_toolbelt' though is only required for 'irmc_fwbios_update.py' module and it is stated there.

**Comment by akumch** [comment]
As of today, new release V1.2 states requirements correctly.
