### ISSUE TITLE
Error running example related toy import in irmc_facts.p

### ISSUE THREAD

**Issue by jscott0918** [FujitsuPrimergy/fujitsu-ansible-irmc-integration#3]
Trying to get started by running a simple get_facts example. I get the following error. I've made sure all of the dependencies are met (`pip install future requests urllib3 requests_toolbelt` succeeded).

Dump below of error

jscott@scoj-mac-0:fujitsu-ansible-irmc-integration/examples $ ansible-playbook -vvv get_server_facts.yml
No config file found; using defaults

PLAYBOOK: get_server_facts.yml *************************************************
1 plays in get_server_facts.yml

PLAY [get server facts via iRMC] ***********************************************

TASK [Get basic server and iRMC facts] *****************************************
task path: /Users/jscott/.ansible/plugins/modules/fujitsu-ansible-irmc-integration/examples/get_server_facts.yml:26
fatal: [spc1]: FAILED! => {"failed": true, "msg": "error importing module in /Users/jscott/.ansible/plugins/modules/fujitsu-ansible-irmc-integration/library/irmc_facts.py, expecting format like 'from ansible.module_utils.<lib name> import *'"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @get_server_facts.retry

PLAY RECAP *********************************************************************
spc1                       : ok=0    changed=0    unreachable=0    failed=1

**Comment by akumch** [comment]
Please note the documentation, section Getting Started:
> Copy the example playbooks to the main folder and adapt the and the variables in group_vars to your environment and run the playbooks.

It seems you started the playbook directly from the  examples folder:
> TASK [Get basic server and iRMC facts] *****************************************
> task path: /Users/jscott/.ansible/plugins/modules/fujitsu-ansible-irmc-integration/examples/get_server_facts.yml:26

Does the error persist if you copy the playbook into the main folder?

**Comment by akumch** [comment]
I'm at a loss as to what your problem might be. We cannot reproduce it.
We tried the package in every constellation of user rights and file system location we could think of and it always worked perfectly.

So now I have to guess:
- Which OS?
- Which version of Ansible?
- When running the playbook from the main package folder: Is the problem still that Ansible cannot import modules from irmc_facts.py?
- Does the problem persist if you place the pack outside of the Ansible modules, e.g. in /Users/jscott/fujitsu-ansible-irmc-integration?

**Comment by jscott0918** [comment]
This was failing under RHEL 6.9 and Mac OS 10.13.6 High Sierra. I created a fresh install of RHEL 7.5, installed ansible, pulled the repo, copied the examples to the root directory and everything worked fine. Something is wrong with my python path on my laptop/old workstation so i'm fine closing this issue and i'll just sort it out on my own machines.
