### ISSUE TITLE
Using ansible for firmware upgrades

### ISSUE THREAD

**Issue by Klaas-** [FujitsuPrimergy/fujitsu-ansible-irmc-integration#5]
Hi,
this is more a question than an issue with the ansible code -- are the best practices by fujitsu for large scale firmware updates via ansible? I want to put firmware updates into our automated (OS) patch process but it seems I'm the first one attempting that ;)
My current workaround is to just use the Update Manager Express cli and downloading the UpdateDVD manually but I would very much like to automate this properly using a real local mirror that can refresh itself and then have an ansible role that properly updates all firmware components through irmc

Greetings
Klaas

**Comment by akumch** [comment]
Hi Klaas,

As far as I could find out (not being PM) there is no overall best practices update strategy. 
It simply depends on the environment you are working in (e.g. when working with vCenter, update via the vCenter Integration).

The Ansible modules are perfectly capable of managing an Offline or Online update for each individual iRMC via a local (well, or the official) Update Repository. Naturally there may be scaling issues with your repository and you probably want to make very sure not to reboot a server while it is in a critical business phase, but all of these considerations are besides and outside the Ansible Modules themselves. Note that the preparation phase can be at any time while the execution phase requires a server to restart.

From a technical standpoint (which is the only one I can really take) there is no reason to use the Ansible modules in a large scale environment if all boundary conditions are taken into account.

This may not be the definitive answer you have been looking for, but it is the only one I can honestly give.

Best regards,
Andrea

**Comment by Klaas-** [comment]
Hi,
thanks for the answer I have a couple of follow up questions:
* where would I find the firmware update repository of fujitsu? only thing that comes close is the UpdateDVD. But I still need to download that via the website and can't mirror that automatically (rsync/yum/whatever). 
* ansible role for firmware updates: https://github.com/FujitsuPrimergy/fujitsu-ansible-irmc-integration/blob/master/examples/irmc_fwbios_update_examples.yml gives an example of fw updates; do you actually have a role that will take the updatedvd/repository and select the newest applicable version on its own? otherwise I'll have to keep updating my play to use the firmware versions I wish to install
* the updatedvd also has fw updates for the storage controller/fc/lan/... can I update those via irmc aswell? example only mentions bios and irmc

greetings
klaas

**Comment by akumch** [comment]
Hi,

We may be talking about different topics.

What I was thinking of:

For general FW update of servers please consider the eLCM Update Management: https://techcommunity.ts.fujitsu.com/en/servers/d/uid-33f876db-7e84-f041-8502-6f0188330448.html

eLCM enables you to (online or offline) update the firmware of any controller within your server. It also means to buy an eLCM license for each of your iRMCs. This process can be automated via Ansible via the elcm_ modules. You only need to keep your eLCM repository up-to-date or use the official repository which will be kept up-to-date by Fujitsu.
See the elcm_ modules for links to more documentation.

eLCM uses the Default Update Repsoitory which every iRMC knows about by default (you can setup your own, outlines are described here: http://manuals.ts.fujitsu.com/file/13709/sv-vmware-fwbios-update-wp-en.pdf).

More information about local system update: http://manuals.ts.fujitsu.com/file/9422/sv-locsysupd-en.pdf

What I think you are talking about:
BIOS and iRMC firmware can be updated outside of eLCM but where you keep your files and how to keep them up-to-date is up to you.

Best regards,
Andrea

**Comment by Klaas-** [comment]
Hi,
yes I am definitely talking about updates without eLCM :)
so what I can ready from your answer is you don't want to create a competing product for eLCM, which I totally understand. I don't think eLCM is an option for me because I need to integrate firmware updates into my OS upgrade workflow.

So for now this means I'll just create a simple role that is based on UpdateMgrExpress from the UpdateDVD. But that means I have to have java on every fujitsu server :(

Thanks for the advice.

Greetings
Klaas
